import Phaser from 'phaser';
import type { Action, Condition, DialogueNode, GameProtocol, QuestProgress, SaveData } from '../types';
import { createInitialSave, playerStats } from './content';

type DialogueHandler = (speaker: string, portraitSrc: string | undefined, lines: string[], choices: string[] | undefined, done: (choice?: number) => void) => void;
export type MinimapState = { player: Point; npcs: Point[]; enemies: Point[]; exits: Point[] }; type Point = { x: number; y: number };
export interface GameViewState { hp: number; maxHp: number; level: number; xp: number; levelXp: number; requiredXp: number; nextXp: number; attack: number; defense: number; objective: string; mapId: string; mapName: string; worldX: number; worldY: number; chapter: string; quests: Record<string, QuestProgress>; inventory: Record<string, number>; equipment: Record<string, string | null>; skills: string[]; effects: string[]; currencies: Record<string, number>; minimap: MinimapState }

export class GameScene extends Phaser.Scene {
  private player!: Phaser.Physics.Arcade.Sprite; private npcs!: Phaser.Physics.Arcade.StaticGroup; private objects!: Phaser.Physics.Arcade.StaticGroup; private enemies!: Phaser.Physics.Arcade.Group;
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys; private keys!: Record<'up'|'down'|'left'|'right'|'interact'|'attack', Phaser.Input.Keyboard.Key>;
  private dataState: SaveData; private startedAt = Date.now(); private lastAttack = 0; private lastHurt = 0; private frozen = false; private transitioning = false; private dialogue!: DialogueHandler; private skillReadyAt: Record<string, number> = {}; private tileCollisionLayers: Phaser.Tilemaps.TilemapLayer[] = [];

  constructor(private config: GameProtocol, initialSave: SaveData | null, private onChange: (data: SaveData) => void) { super('world'); this.dataState = initialSave ?? createInitialSave(config); }
  preload(): void {
    Object.entries(this.config.assets.images).forEach(([id, asset]) => this.load.image(id, asset.src));
    Object.entries(this.config.assets.spritesheets).forEach(([id, asset]) => this.load.spritesheet(id, asset.src, { frameWidth: asset.frameWidth, frameHeight: asset.frameHeight }));
    Object.entries(this.config.assets.audio).forEach(([id, asset]) => this.load.audio(id, asset.src));
    Object.entries(this.config.maps).forEach(([id, map]) => { if (map.tiled) this.load.tilemapTiledJSON(`tiled:${id}`, map.tiled.json); });
  }
  create(): void {
    this.transitioning = false; this.frozen = false; this.lastAttack = 0; this.lastHurt = 0; this.startedAt = Date.now(); this.createTextures(); Object.entries(this.config.assets.animations ?? {}).forEach(([id,a])=>{if(!this.anims.exists(id))this.anims.create({key:id,frames:this.anims.generateFrameNumbers(a.texture,{start:a.start,end:a.end}),frameRate:a.frameRate,repeat:a.repeat??-1});}); this.cursors = this.input.keyboard!.createCursorKeys(); this.keys = this.input.keyboard!.addKeys({ up:'W',down:'S',left:'A',right:'D',interact:'E',attack:'SPACE' }) as typeof this.keys; this.dialogue = this.registry.get('dialogue') as DialogueHandler;
    this.tileCollisionLayers=[]; this.buildMap(this.dataState.player.mapId, this.dataState.player); this.progressByEvent('visit', this.dataState.player.mapId);
    this.time.addEvent({ delay: this.config.game.autosaveSeconds * 1000, loop: true, callback: () => this.persist() }); this.emitState();
  }
  private buildTiledMap(id:string):void {const def=this.config.maps[id].tiled;if(!def)return;const tilemap=this.make.tilemap({key:`tiled:${id}`});const sets=def.tilesets.map(t=>tilemap.addTilesetImage(t.name,t.image)).filter((x):x is Phaser.Tilemaps.Tileset=>x!==null);tilemap.layers.forEach(layer=>{const created=tilemap.createLayer(layer.name,sets,0,0);if(created&&layer.name===def.collisionLayer){created.setCollisionByProperty({collides:true});this.tileCollisionLayers.push(created);}});}
  update(time: number): void {
    if (!this.player?.active) return; const body = this.player.body as Phaser.Physics.Arcade.Body; body.setVelocity(0);
    if (!this.frozen && !this.transitioning) { const v = new Phaser.Math.Vector2(Number(this.cursors.right.isDown||this.keys.right.isDown)-Number(this.cursors.left.isDown||this.keys.left.isDown),Number(this.cursors.down.isDown||this.keys.down.isDown)-Number(this.cursors.up.isDown||this.keys.up.isDown)); if(v.lengthSq())v.normalize().scale(175); body.setVelocity(v.x,v.y); if(Phaser.Input.Keyboard.JustDown(this.keys.interact))this.interact(); if(Phaser.Input.Keyboard.JustDown(this.keys.attack))this.attack(time); }
    this.updateEnemies(time); this.updateEffects(); this.checkExits(); if(Math.floor(time/150)!==Math.floor((time-this.game.loop.delta)/150))this.emitState();
  }
  snapshot(): SaveData { this.dataState.player.x=Math.round(this.player.x); this.dataState.player.y=Math.round(this.player.y); this.dataState.savedAt=new Date().toISOString(); return structuredClone(this.dataState); }
  restore(save: SaveData): void { this.dataState=structuredClone(save); this.scene.restart(); }
  syncView(): void { this.emitState(); }
  useItem(itemId: string): void { const item=this.config.items[itemId]; if(!item||item.type!=='consumable'||!(this.dataState.player.inventory[itemId]>0))return; this.dataState.player.inventory[itemId]-=1; this.applyActions(item.actions??[]); this.toast(`${item.name}을 사용했습니다.`); this.persist(); this.emitState(); }
  equipItem(itemId:string):void {const item=this.config.items[itemId];if(!item||item.type!=='equipment'||!item.slot||(this.dataState.player.inventory[itemId]??0)<1)return;const previous=this.dataState.player.equipment[item.slot];if(previous===itemId)this.dataState.player.equipment[item.slot]=null;else this.dataState.player.equipment[item.slot]=itemId;this.toast(previous===itemId?`${item.name} 장착 해제`:`${item.name} 장착`);this.persist();this.emitState();}
  useSkill(skillId:string):void {const skill=this.config.skills[skillId];const now=Date.now();if(!skill||!this.dataState.player.skills.includes(skillId)||now<(this.skillReadyAt[skillId]??0))return;this.skillReadyAt[skillId]=now+skill.cooldownMs;if(skill.target==='self')this.applyActions(skill.actions??[]);else{const stats=this.currentStats();this.enemies.getChildren().forEach(c=>{const enemy=c as Phaser.Physics.Arcade.Sprite;if(!enemy.active||Phaser.Math.Distance.BetweenPoints(this.player,enemy)>skill.range)return;const def=this.config.monsters[String(enemy.getData('monsterId'))],hp=Number(enemy.getData('hp'))-Math.max(1,Math.round(stats.attack*skill.power)-def.stats.defense);enemy.setData('hp',hp);if(hp<=0)this.defeatEnemy(enemy);});}this.toast(`${skill.name} 사용`);this.persist();this.emitState();}
  buyItem(shopId:string,itemId:string):void {const shop=this.config.shops[shopId],entry=shop?.items.find(x=>x.itemId===itemId);if(!shop||!entry)return;const money=this.dataState.player.currencies[shop.currency]??0;if(money<entry.buy)return this.toast('화폐가 부족합니다.');this.dataState.player.currencies[shop.currency]=money-entry.buy;this.addItem(itemId,1);this.persist();this.emitState();}
  sellItem(shopId:string,itemId:string):void {const shop=this.config.shops[shopId],entry=shop?.items.find(x=>x.itemId===itemId);if(!shop||!entry?.sell||(this.dataState.player.inventory[itemId]??0)<1)return;this.addItem(itemId,-1);this.dataState.player.currencies[shop.currency]=(this.dataState.player.currencies[shop.currency]??0)+entry.sell;this.persist();this.emitState();}
  updateSettings(settings:Partial<SaveData['settings']>):void {Object.assign(this.dataState.settings,settings);this.sound.mute=this.dataState.settings.muted;this.sound.volume=this.dataState.settings.musicVolume;this.persist();}

  private buildMap(id:string,spawn:Point):void { const map=this.config.maps[id]; this.cameras.main.setBackgroundColor(map.ground); if(map.tiled)this.buildTiledMap(id);else{for(let x=0;x<960;x+=32)for(let y=0;y<540;y+=32)this.add.image(x+16,y+16,'ground').setTint(Phaser.Display.Color.HexStringToColor(map.ground).color).setAlpha(.96);if(map.backgroundImage)this.add.image(480,270,map.backgroundImage).setDisplaySize(960,540).setAlpha(map.backgroundAlpha??1);this.add.rectangle(480,270,960,108,Phaser.Display.Color.HexStringToColor(map.path).color,.72);}
    this.npcs=this.physics.add.staticGroup(); map.npcs.forEach(p=>{const def=this.config.npcs[p.npcId];const sprite=this.npcs.create(p.x,p.y,def.texture) as Phaser.Physics.Arcade.Sprite;sprite.setScale(def.scale??1).refreshBody().setData('npcId',p.npcId);if(def.color)sprite.setTint(Phaser.Display.Color.HexStringToColor(def.color).color);this.add.text(p.x,p.y-35,def.name,{fontFamily:'sans-serif',fontSize:'11px',color:'#fff2c5',backgroundColor:'#152629aa',padding:{x:4,y:2}}).setOrigin(.5);}); map.exits.forEach(e=>{this.add.rectangle(e.x,e.y,e.width,e.height,0xffdc89,.16).setStrokeStyle(2,0xffdc89,.55);const arrows={north:'▲',east:'▶',south:'▼',west:'◀'},lx=e.direction==='west'?42:e.direction==='east'?918:e.x,ly=e.direction==='north'?38:e.direction==='south'?502:e.y-88;this.add.text(lx,ly,`${arrows[e.direction]} ${e.label}`,{fontFamily:'sans-serif',fontSize:'12px',color:'#ffe6a5',backgroundColor:'#172a32dd',padding:{x:6,y:3}}).setOrigin(.5);});
    this.objects=this.physics.add.staticGroup();(map.objects??[]).filter(o=>(o.conditions??[]).every(c=>this.checkCondition(c))).forEach(o=>{const sprite=this.objects.create(o.x,o.y,o.texture??'object') as Phaser.Physics.Arcade.Sprite;sprite.setDisplaySize(o.width,o.height).refreshBody().setData('object',o);this.add.text(o.x,o.y-o.height/2-10,o.name,{fontFamily:'sans-serif',fontSize:'10px',color:'#dce8c8'}).setOrigin(.5);});this.player=this.physics.add.sprite(spawn.x,spawn.y,this.config.player.texture).setScale(this.config.player.scale??1).setCollideWorldBounds(true).setDepth(2);if(this.config.player.animation)this.player.play(this.config.player.animation);this.enemies=this.physics.add.group();this.physics.add.collider(this.player,this.npcs);this.tileCollisionLayers.forEach(layer=>this.physics.add.collider(this.player,layer));this.objects.getChildren().filter(c=>Boolean((c as Phaser.Physics.Arcade.Sprite).getData('object').solid)).forEach(c=>this.physics.add.collider(this.player,c as Phaser.Physics.Arcade.Sprite));map.spawns.forEach(zone=>{this.add.rectangle(zone.x+zone.width/2,zone.y+zone.height/2,zone.width,zone.height,0xe5bd71,.035).setStrokeStyle(1,0xf0c77a,.18);for(let i=0;i<zone.max;i++)this.spawnEnemy(zone);this.time.addEvent({delay:zone.respawnMs,loop:true,callback:()=>{const count=this.enemies.getChildren().filter(c=>(c as Phaser.Physics.Arcade.Sprite).active&&(c as Phaser.Physics.Arcade.Sprite).getData('zone')===zone.id).length;if(count<zone.max)this.spawnEnemy(zone);}});});if(map.music){const audio=this.config.assets.audio[map.music];this.sound.stopAll();this.sound.play(map.music,{volume:audio.volume??1,loop:audio.loop??true});}
  }
  private createTextures():void {if(this.textures.exists('ground'))return;const g=this.make.graphics({x:0,y:0},false);g.fillStyle(0xffffff).fillRect(0,0,32,32).fillStyle(0xd8e6bc,.14).fillCircle(7,8,3).generateTexture('ground',32,32).clear();g.fillStyle(0xd4c078).fillRect(4,4,24,24).fillStyle(0x6b5b3b).fillRect(9,9,14,14).generateTexture('object',32,32);g.destroy();}
  private interact():void {const object=this.objects?.getChildren().map(c=>c as Phaser.Physics.Arcade.Sprite).find(o=>Phaser.Math.Distance.BetweenPoints(this.player,o)<70);if(object){const def=object.getData('object') as NonNullable<GameProtocol['maps'][string]['objects']>[number];this.applyActions(def.actions??[]);this.toast(`${def.name} 상호작용`);this.persist();return;}let nearest:Phaser.Physics.Arcade.Sprite|null=null,distance=78;this.npcs.getChildren().forEach(c=>{const npc=c as Phaser.Physics.Arcade.Sprite,d=Phaser.Math.Distance.BetweenPoints(this.player,npc);if(d<distance){nearest=npc;distance=d;}});if(!nearest)return this.toast('가까이에 상호작용 대상이 없습니다.');this.talk(String((nearest as Phaser.Physics.Arcade.Sprite).getData('npcId')));}
  private talk(npcId:string):void {this.frozen=true;this.progressByEvent('talk',npcId);const npc=this.config.npcs[npcId],nodes=this.config.dialogues[npc.dialogue];const node=nodes.find(n=>(n.conditions??[]).every(c=>this.checkCondition(c)))??nodes[nodes.length-1];this.runNode(nodes,node,npc.portrait,()=>{this.frozen=false;this.persist();this.emitState();if(npc.shop)this.events.emit('shop',npc.shop);});}
  private runNode(nodes:DialogueNode[],node:DialogueNode,defaultPortrait:string|undefined,done:()=>void):void {const portraitId=node.portrait??defaultPortrait;const portraitSrc=portraitId?this.config.assets.images[portraitId]?.src:undefined;this.dialogue(node.speaker,portraitSrc,node.text,node.choices?.filter(c=>(c.conditions??[]).every(x=>this.checkCondition(x))).map(c=>c.text),(choice)=>{this.applyActions(node.actions??[]);if(choice!==undefined&&node.choices){const available=node.choices.filter(c=>(c.conditions??[]).every(x=>this.checkCondition(x)));this.applyActions(available[choice]?.actions??[]);const next=available[choice]?.next;if(next){const found=nodes.find(n=>n.id===next);if(found)return this.runNode(nodes,found,defaultPortrait,done);}}if(node.next){const found=nodes.find(n=>n.id===node.next);if(found)return this.runNode(nodes,found,defaultPortrait,done);}done();});}
  private checkCondition(c:Condition):boolean {let actual:string|number|boolean|undefined;if(c.type==='questStatus')actual=this.dataState.world.quests[c.id]?.status;else if(c.type==='objective'){const[q,o]=c.id.split('.');actual=this.dataState.world.quests[q]?.objectives[o]??0;}else if(c.type==='level')actual=this.dataState.player.level;else if(c.type==='hasItem')actual=this.dataState.player.inventory[c.id]??0;else if(c.type==='currency')actual=this.dataState.player.currencies[c.id]??0;else if(c.type==='equipped')actual=Object.values(this.dataState.player.equipment).includes(c.id);else if(c.type==='chapter')actual=this.dataState.world.chapter;else actual=this.dataState.world.flags[c.id]??false;if(c.operator==='gte')return Number(actual)>=Number(c.value);if(c.operator==='lte')return Number(actual)<=Number(c.value);return actual===c.value;}
  private applyActions(actions:Action[]):void {actions.forEach(a=>{if(a.type==='startQuest'&&a.id)this.dataState.world.quests[a.id].status='active';if(a.type==='completeQuest'&&a.id)this.completeQuest(a.id);if(a.type==='failQuest'&&a.id)this.dataState.world.quests[a.id].status='failed';if(a.type==='objective'&&a.id&&a.objectiveId)this.progressObjective(a.id,a.objectiveId,a.amount??1);if(a.type==='giveItem'&&a.id)this.addItem(a.id,a.amount??1);if(a.type==='takeItem'&&a.id)this.addItem(a.id,-(a.amount??1));if(a.type==='heal')this.dataState.player.hp=Math.min(this.currentStats().maxHp,this.dataState.player.hp+(a.amount??0));if(a.type==='setFlag'&&a.id)this.dataState.world.flags[a.id]=a.value??true;if(a.type==='xp')this.addXp(a.amount??0);if(a.type==='currency'&&a.id)this.dataState.player.currencies[a.id]=(this.dataState.player.currencies[a.id]??0)+(a.amount??0);if(a.type==='learnSkill'&&a.id&&!this.dataState.player.skills.includes(a.id))this.dataState.player.skills.push(a.id);if(a.type==='effect'&&a.id)this.addEffect(a.id,a.durationMs);if(a.type==='cutscene'&&a.id)this.runCutscene(a.id);if(a.type==='chapter'&&a.id)this.dataState.world.chapter=a.id;if(a.type==='ending'&&a.id)this.unlockEnding(a.id);if(a.type==='teleport'&&a.mapId&&this.config.maps[a.mapId]){this.dataState.player.mapId=a.mapId;this.dataState.player.x=a.x??this.config.maps[a.mapId].spawn.x;this.dataState.player.y=a.y??this.config.maps[a.mapId].spawn.y;}});}
  private spawnEnemy(zone:GameProtocol['maps'][string]['spawns'][number]):void {const def=this.config.monsters[zone.monsterId],enemy=this.enemies.create(Phaser.Math.Between(zone.x,zone.x+zone.width),Phaser.Math.Between(zone.y,zone.y+zone.height),def.texture) as Phaser.Physics.Arcade.Sprite;enemy.setScale(def.scale??1).setData({monsterId:zone.monsterId,zone:zone.id,hp:def.stats.maxHp});}
  private attack(time:number):void {if(time-this.lastAttack<this.config.combat.attackCooldownMs)return;this.lastAttack=time;const slash=this.add.circle(this.player.x,this.player.y,this.config.combat.attackRange*.6,0xffefb0,.38).setDepth(3);this.tweens.add({targets:slash,scale:1.55,alpha:0,duration:180,onComplete:()=>slash.destroy()});const stats=this.currentStats();this.enemies.getChildren().forEach(c=>{const e=c as Phaser.Physics.Arcade.Sprite;if(!e.active||Phaser.Math.Distance.BetweenPoints(this.player,e)>=this.config.combat.attackRange)return;const def=this.config.monsters[String(e.getData('monsterId'))],damage=Math.max(1,stats.attack-def.stats.defense),hp=Number(e.getData('hp'))-damage;e.setData('hp',hp).setTintFill(0xffffff);this.time.delayedCall(90,()=>e.active&&e.clearTint());if(hp<=0)this.defeatEnemy(e);});}
  private defeatEnemy(enemy:Phaser.Physics.Arcade.Sprite):void {const id=String(enemy.getData('monsterId')),def=this.config.monsters[id];enemy.destroy();this.dataState.world.defeated[id]=(this.dataState.world.defeated[id]??0)+1;this.progressByEvent('kill',id);this.addXp(def.xp);def.drops.forEach(drop=>{if(Math.random()<=drop.chance)this.addItem(drop.itemId,Phaser.Math.Between(drop.min,drop.max));});this.toast(`${def.name} 처치 · 경험치 +${def.xp}`);this.persist();}
  private updateEnemies(time:number):void {if(this.frozen)return;this.enemies.getChildren().forEach(c=>{const e=c as Phaser.Physics.Arcade.Sprite;if(!e.active)return;const def=this.config.monsters[String(e.getData('monsterId'))],distance=Phaser.Math.Distance.BetweenPoints(this.player,e),body=e.body as Phaser.Physics.Arcade.Body;let speed=def.speed;const ratio=Number(e.getData('hp'))/def.stats.maxHp;const pattern=def.patterns?.find(p=>ratio<=(p.hpBelow??1)&&time-Number(e.getData(`pattern:${p.id}`)??0)>=p.cooldownMs);if(pattern){e.setData(`pattern:${pattern.id}`,time);if(pattern.type==='dash')speed*=Math.max(1,pattern.power);if(pattern.type==='area'&&distance<90)this.dataState.player.hp=Math.max(0,this.dataState.player.hp-Math.max(1,Math.round(def.stats.attack*pattern.power)-this.currentStats().defense));}if(distance<def.aggroRange)this.physics.moveToObject(e,this.player,speed);else body.setVelocity(0);if(distance<32&&time-this.lastHurt>this.config.combat.invulnerabilityMs){this.lastHurt=time;const damage=Math.max(1,def.stats.attack-this.currentStats().defense);this.dataState.player.hp=Math.max(0,this.dataState.player.hp-damage);this.cameras.main.shake(90,.007);if(this.dataState.player.hp<=0)this.respawn();this.emitState();}});}
  private respawn():void {const map=this.config.maps[this.dataState.player.mapId];this.dataState.player.hp=this.currentStats().maxHp;this.player.setPosition(map.spawn.x,map.spawn.y);this.toast('쓰러졌습니다. 지역 입구에서 다시 시작합니다.');this.persist();}
  private checkExits():void {if(this.transitioning)return;const map=this.config.maps[this.dataState.player.mapId],exit=map.exits.find(e=>Phaser.Geom.Rectangle.Contains(new Phaser.Geom.Rectangle(e.x-e.width/2,e.y-e.height/2,e.width,e.height),this.player.x,this.player.y));if(!exit)return;if(!(exit.conditions??[]).every(c=>this.checkCondition(c))){this.toast(exit.lockedText??'아직 이 길을 이용할 수 없습니다.');if(exit.direction==='west')this.player.x+=24;if(exit.direction==='east')this.player.x-=24;if(exit.direction==='north')this.player.y+=24;if(exit.direction==='south')this.player.y-=24;return;}this.transitioning=true;const axisX=Phaser.Math.Clamp(this.player.x,48,912),axisY=Phaser.Math.Clamp(this.player.y,48,492);this.dataState.player.mapId=exit.to;if(exit.direction==='east'){this.dataState.player.x=48;this.dataState.player.y=axisY;}if(exit.direction==='west'){this.dataState.player.x=912;this.dataState.player.y=axisY;}if(exit.direction==='north'){this.dataState.player.x=axisX;this.dataState.player.y=492;}if(exit.direction==='south'){this.dataState.player.x=axisX;this.dataState.player.y=48;}this.progressByEvent('visit',exit.to);this.persist();this.cameras.main.fadeOut(220,10,18,20);this.time.delayedCall(240,()=>this.scene.restart());}
  private progressByEvent(type:'kill'|'talk'|'visit'|'collect',targetId:string,amount=1):void {Object.entries(this.config.quests).forEach(([id,q])=>{const progress=this.dataState.world.quests[id];if(progress?.status!=='active')return;q.objectives.filter(o=>o.type===type&&o.targetId===targetId).forEach(o=>this.progressObjective(id,o.id,amount));});}
  private progressObjective(questId:string,objectiveId:string,amount:number):void {const progress=this.dataState.world.quests[questId],def=this.config.quests[questId];if(!progress||progress.status!=='active')return;const objective=def.objectives.find(o=>o.id===objectiveId);if(!objective)return;progress.objectives[objectiveId]=Math.min(objective.target,(progress.objectives[objectiveId]??0)+amount);if(def.objectives.every(o=>(progress.objectives[o.id]??0)>=o.target))progress.status='ready';}
  private completeQuest(id:string):void {const q=this.dataState.world.quests[id],def=this.config.quests[id];if(!q||q.status==='completed')return;q.status='completed';if(!q.rewarded){this.addXp(def.rewards.xp??0);Object.entries(def.rewards.items??{}).forEach(([item,n])=>this.addItem(item,n));q.rewarded=true;this.toast(`퀘스트 완료 · ${def.title}`);}}
  private addItem(id:string,amount:number):void {const def=this.config.items[id];if(!def)return;const before=this.dataState.player.inventory[id]??0;this.dataState.player.inventory[id]=Phaser.Math.Clamp(before+amount,0,def.maxStack);if(amount>0){this.progressByEvent('collect',id,amount);this.toast(`${def.name} +${amount}`);}}
  private addXp(amount:number):void {this.dataState.player.xp+=amount;const curve=this.config.player.xpCurve;while(this.dataState.player.level<curve.length&&this.dataState.player.xp>=curve[this.dataState.player.level]){this.dataState.player.level++;const stats=this.currentStats();this.dataState.player.hp=stats.maxHp;this.toast(`레벨 ${this.dataState.player.level} 달성!`);}}
  private currentStats():ReturnType<typeof playerStats>{const stats=playerStats(this.config,this.dataState.player.level);Object.values(this.dataState.player.equipment).forEach(id=>{if(!id)return;const modifiers=this.config.items[id]?.modifiers;stats.maxHp+=modifiers?.maxHp??0;stats.attack+=modifiers?.attack??0;stats.defense+=modifiers?.defense??0;});this.dataState.player.effects.forEach(active=>{const modifiers=this.config.effects[active.id]?.modifiers;stats.maxHp+=modifiers?.maxHp??0;stats.attack+=modifiers?.attack??0;stats.defense+=modifiers?.defense??0;});return stats;}
  private addEffect(id:string,duration?:number):void {const def=this.config.effects[id];if(!def)return;const now=Date.now(),existing=this.dataState.player.effects.find(e=>e.id===id);const value={id,expiresAt:now+(duration??def.durationMs),nextTick:now+(def.tickMs??def.durationMs)};if(existing)Object.assign(existing,value);else this.dataState.player.effects.push(value);}
  private updateEffects():void {const now=Date.now();this.dataState.player.effects.forEach(active=>{const def=this.config.effects[active.id];if(!def||now<active.nextTick)return;active.nextTick=now+(def.tickMs??def.durationMs);this.dataState.player.hp=Phaser.Math.Clamp(this.dataState.player.hp+(def.healPerTick??0)-(def.damagePerTick??0),0,this.currentStats().maxHp);});this.dataState.player.effects=this.dataState.player.effects.filter(e=>e.expiresAt>now);}
  private runCutscene(id:string):void {const scene=this.config.cutscenes[id];if(!scene)return;this.frozen=true;let delay=0;scene.steps.forEach(step=>{this.time.delayedCall(delay,()=>{if(step.type==='text'&&step.text)this.toast(step.text);if(step.type==='camera')this.cameras.main.zoomTo(step.zoom??1,step.durationMs??300);if(step.type==='action')this.applyActions(step.actions??[]);});delay+=step.durationMs??(step.type==='text'?1600:0);});this.time.delayedCall(delay,()=>{this.frozen=false;});}
  private unlockEnding(id:string):void {const ending=this.config.endings[id];if(!ending||(ending.conditions??[]).some(c=>!this.checkCondition(c)))return;if(!this.dataState.world.endings.includes(id))this.dataState.world.endings.push(id);this.events.emit('ending',ending);}
  private persist():void {this.dataState.playTime+=Math.floor((Date.now()-this.startedAt)/1000);this.startedAt=Date.now();this.onChange(this.snapshot());}
  private emitState():void {if(!this.player)return;const active=Object.entries(this.dataState.world.quests).find(([,q])=>q.status==='active'||q.status==='ready');let objective='새로운 의뢰를 찾아보세요';if(active){const def=this.config.quests[active[0]],q=active[1],next=def.objectives.find(o=>(q.objectives[o.id]??0)<o.target);objective=q.status==='ready'?`${def.giver}에게 보고하세요`:next?`${next.label} ${q.objectives[next.id]??0}/${next.target}`:def.title;}const stats=this.currentStats(),mapId=this.dataState.player.mapId,map=this.config.maps[mapId],levelStart=this.config.player.xpCurve[Math.max(0,this.dataState.player.level-1)]??0,nextXp=this.config.player.xpCurve[this.dataState.player.level]??this.dataState.player.xp,minimap:MinimapState={player:{x:this.player.x,y:this.player.y},npcs:map.npcs.map(n=>({x:n.x,y:n.y})),enemies:this.enemies?.getChildren().filter(e=>(e as Phaser.Physics.Arcade.Sprite).active).map(e=>({x:(e as Phaser.Physics.Arcade.Sprite).x,y:(e as Phaser.Physics.Arcade.Sprite).y}))??[],exits:map.exits.map(e=>({x:e.x,y:e.y}))};this.events.emit('state',{hp:this.dataState.player.hp,maxHp:stats.maxHp,level:this.dataState.player.level,xp:this.dataState.player.xp,levelXp:this.dataState.player.xp-levelStart,requiredXp:Math.max(1,nextXp-levelStart),nextXp,attack:stats.attack,defense:stats.defense,objective,mapId,mapName:map.name,worldX:map.grid.x,worldY:map.grid.y,chapter:this.dataState.world.chapter,quests:structuredClone(this.dataState.world.quests),inventory:{...this.dataState.player.inventory},equipment:{...this.dataState.player.equipment},skills:[...this.dataState.player.skills],effects:this.dataState.player.effects.map(e=>e.id),currencies:{...this.dataState.player.currencies},minimap} satisfies GameViewState);}
  private toast(message:string):void {this.events.emit('toast',message);}
}
