import Phaser from 'phaser';
import type { Action, Condition, DialogueNode, GameProtocol, QuestProgress, SaveData } from '../types';
import { createInitialSave, playerStats } from './content';

type DialogueHandler = (speaker: string, lines: string[], choices: string[] | undefined, done: (choice?: number) => void) => void;
export type MinimapState = { player: Point; npcs: Point[]; enemies: Point[]; exits: Point[] }; type Point = { x: number; y: number };
export interface GameViewState { hp: number; maxHp: number; level: number; xp: number; nextXp: number; attack: number; defense: number; objective: string; mapName: string; quests: Record<string, QuestProgress>; inventory: Record<string, number>; minimap: MinimapState }

export class GameScene extends Phaser.Scene {
  private player!: Phaser.Physics.Arcade.Sprite; private npcs!: Phaser.Physics.Arcade.StaticGroup; private enemies!: Phaser.Physics.Arcade.Group;
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys; private keys!: Record<'up'|'down'|'left'|'right'|'interact'|'attack', Phaser.Input.Keyboard.Key>;
  private dataState: SaveData; private startedAt = Date.now(); private lastAttack = 0; private lastHurt = 0; private frozen = false; private transitioning = false; private dialogue!: DialogueHandler;

  constructor(private config: GameProtocol, initialSave: SaveData | null, private onChange: (data: SaveData) => void) { super('world'); this.dataState = initialSave ?? createInitialSave(config); }
  create(): void {
    this.startedAt = Date.now(); this.createTextures(); this.cursors = this.input.keyboard!.createCursorKeys(); this.keys = this.input.keyboard!.addKeys({ up:'W',down:'S',left:'A',right:'D',interact:'E',attack:'SPACE' }) as typeof this.keys; this.dialogue = this.registry.get('dialogue') as DialogueHandler;
    this.buildMap(this.dataState.player.mapId, this.dataState.player); this.progressByEvent('visit', this.dataState.player.mapId);
    this.time.addEvent({ delay: this.config.game.autosaveSeconds * 1000, loop: true, callback: () => this.persist() }); this.emitState();
  }
  update(time: number): void {
    if (!this.player?.active) return; const body = this.player.body as Phaser.Physics.Arcade.Body; body.setVelocity(0);
    if (!this.frozen && !this.transitioning) { const v = new Phaser.Math.Vector2(Number(this.cursors.right.isDown||this.keys.right.isDown)-Number(this.cursors.left.isDown||this.keys.left.isDown),Number(this.cursors.down.isDown||this.keys.down.isDown)-Number(this.cursors.up.isDown||this.keys.up.isDown)); if(v.lengthSq())v.normalize().scale(175); body.setVelocity(v.x,v.y); if(Phaser.Input.Keyboard.JustDown(this.keys.interact))this.interact(); if(Phaser.Input.Keyboard.JustDown(this.keys.attack))this.attack(time); }
    this.updateEnemies(time); this.checkExits(); if(Math.floor(time/150)!==Math.floor((time-this.game.loop.delta)/150))this.emitState();
  }
  snapshot(): SaveData { this.dataState.player.x=Math.round(this.player.x); this.dataState.player.y=Math.round(this.player.y); this.dataState.savedAt=new Date().toISOString(); return structuredClone(this.dataState); }
  restore(save: SaveData): void { this.dataState=structuredClone(save); this.scene.restart(); }
  useItem(itemId: string): void { const item=this.config.items[itemId]; if(!item||item.type!=='consumable'||!(this.dataState.player.inventory[itemId]>0))return; this.dataState.player.inventory[itemId]-=1; this.applyActions(item.actions??[]); this.toast(`${item.name}을 사용했습니다.`); this.persist(); this.emitState(); }

  private buildMap(id:string,spawn:Point):void { const map=this.config.maps[id]; this.cameras.main.setBackgroundColor(map.ground); for(let x=0;x<960;x+=32)for(let y=0;y<540;y+=32)this.add.image(x+16,y+16,'ground').setTint(Phaser.Display.Color.HexStringToColor(map.ground).color).setAlpha(.96); this.add.rectangle(480,270,960,108,Phaser.Display.Color.HexStringToColor(map.path).color,.72); this.add.text(28,28,`${map.name}\n${map.subtitle}`,{fontFamily:'sans-serif',fontSize:'17px',color:'#f1f2dc',backgroundColor:'#122326cc',padding:{x:12,y:8},lineSpacing:4}).setDepth(4);
    this.npcs=this.physics.add.staticGroup(); map.npcs.forEach(p=>{const def=this.config.npcs[p.npcId];const sprite=this.npcs.create(p.x,p.y,'npc') as Phaser.Physics.Arcade.Sprite;sprite.setTint(Phaser.Display.Color.HexStringToColor(def.color).color).setData('npcId',p.npcId);this.add.text(p.x,p.y-31,def.name,{fontFamily:'sans-serif',fontSize:'11px',color:'#fff2c5',backgroundColor:'#152629aa',padding:{x:4,y:2}}).setOrigin(.5);}); map.exits.forEach(e=>{this.add.rectangle(e.x,e.y,e.width,e.height,0xffdc89,.16).setStrokeStyle(2,0xffdc89,.55);this.add.text(e.x+(e.x<100?14:-14),e.y-91,`↗ ${e.label}`,{fontFamily:'sans-serif',fontSize:'12px',color:'#ffe6a5',backgroundColor:'#172a32cc',padding:{x:6,y:3}}).setOrigin(e.x<100?0:1,.5);});
    this.player=this.physics.add.sprite(spawn.x,spawn.y,'player').setCollideWorldBounds(true).setDepth(2);this.enemies=this.physics.add.group();this.physics.add.collider(this.player,this.npcs);map.spawns.forEach(zone=>{this.add.rectangle(zone.x+zone.width/2,zone.y+zone.height/2,zone.width,zone.height,0xe5bd71,.035).setStrokeStyle(1,0xf0c77a,.18);for(let i=0;i<zone.max;i++)this.spawnEnemy(zone);this.time.addEvent({delay:zone.respawnMs,loop:true,callback:()=>{const count=this.enemies.getChildren().filter(c=>(c as Phaser.Physics.Arcade.Sprite).active&&(c as Phaser.Physics.Arcade.Sprite).getData('zone')===zone.id).length;if(count<zone.max)this.spawnEnemy(zone);}});});
  }
  private createTextures():void {if(this.textures.exists('ground'))return;const g=this.make.graphics({x:0,y:0},false);g.fillStyle(0xffffff).fillRect(0,0,32,32).fillStyle(0xd8e6bc,.14).fillCircle(7,8,3).generateTexture('ground',32,32).clear();g.fillStyle(0xf3c889).fillCircle(16,15,11).fillStyle(0x23404a).fillRect(9,23,14,8).fillStyle(0x172a32).fillCircle(12,14,2).fillCircle(20,14,2).generateTexture('player',32,32).clear();g.fillStyle(0xffffff).fillCircle(16,14,12).fillStyle(0x51362d).fillRect(6,3,20,7).fillStyle(0xeee5ca).fillRect(8,24,16,8).generateTexture('npc',32,32).clear();g.fillStyle(0x82d173).fillEllipse(18,21,34,23).fillStyle(0xc9f2a7).fillCircle(12,17,4).fillStyle(0x17352a).fillCircle(11,16,2).fillCircle(23,16,2).generateTexture('slime',36,34).clear();g.fillStyle(0x89918a).fillTriangle(4,14,10,1,16,13).fillTriangle(20,13,27,1,32,15).fillEllipse(18,20,32,24).fillStyle(0xf1d172).fillCircle(12,18,2).fillCircle(24,18,2).generateTexture('wolf',36,34);g.destroy();}
  private interact():void {let nearest:Phaser.Physics.Arcade.Sprite|null=null,distance=78;this.npcs.getChildren().forEach(c=>{const npc=c as Phaser.Physics.Arcade.Sprite,d=Phaser.Math.Distance.BetweenPoints(this.player,npc);if(d<distance){nearest=npc;distance=d;}});if(!nearest)return this.toast('가까이에 대화할 사람이 없습니다.');this.talk(String((nearest as Phaser.Physics.Arcade.Sprite).getData('npcId')));}
  private talk(npcId:string):void {this.frozen=true;this.progressByEvent('talk',npcId);const npc=this.config.npcs[npcId],nodes=this.config.dialogues[npc.dialogue];const node=nodes.find(n=>(n.conditions??[]).every(c=>this.checkCondition(c)))??nodes[nodes.length-1];this.runNode(nodes,node,()=>{this.frozen=false;this.persist();this.emitState();});}
  private runNode(nodes:DialogueNode[],node:DialogueNode,done:()=>void):void {this.dialogue(node.speaker,node.text,node.choices?.filter(c=>(c.conditions??[]).every(x=>this.checkCondition(x))).map(c=>c.text),(choice)=>{this.applyActions(node.actions??[]);if(choice!==undefined&&node.choices){const available=node.choices.filter(c=>(c.conditions??[]).every(x=>this.checkCondition(x)));this.applyActions(available[choice]?.actions??[]);const next=available[choice]?.next;if(next){const found=nodes.find(n=>n.id===next);if(found)return this.runNode(nodes,found,done);}}if(node.next){const found=nodes.find(n=>n.id===node.next);if(found)return this.runNode(nodes,found,done);}done();});}
  private checkCondition(c:Condition):boolean {let actual:string|number|boolean|undefined;if(c.type==='questStatus')actual=this.dataState.world.quests[c.id]?.status;else if(c.type==='objective'){const[q,o]=c.id.split('.');actual=this.dataState.world.quests[q]?.objectives[o]??0;}else if(c.type==='level')actual=this.dataState.player.level;else if(c.type==='hasItem')actual=this.dataState.player.inventory[c.id]??0;else actual=this.dataState.world.flags[c.id]??false;if(c.operator==='gte')return Number(actual)>=Number(c.value);if(c.operator==='lte')return Number(actual)<=Number(c.value);return actual===c.value;}
  private applyActions(actions:Action[]):void {actions.forEach(a=>{if(a.type==='startQuest'&&a.id)this.dataState.world.quests[a.id].status='active';if(a.type==='completeQuest'&&a.id)this.completeQuest(a.id);if(a.type==='failQuest'&&a.id)this.dataState.world.quests[a.id].status='failed';if(a.type==='objective'&&a.id&&a.objectiveId)this.progressObjective(a.id,a.objectiveId,a.amount??1);if(a.type==='giveItem'&&a.id)this.addItem(a.id,a.amount??1);if(a.type==='takeItem'&&a.id)this.addItem(a.id,-(a.amount??1));if(a.type==='heal')this.dataState.player.hp=Math.min(playerStats(this.config,this.dataState.player.level).maxHp,this.dataState.player.hp+(a.amount??0));if(a.type==='setFlag'&&a.id)this.dataState.world.flags[a.id]=a.value??true;if(a.type==='xp')this.addXp(a.amount??0);if(a.type==='teleport'&&a.mapId&&this.config.maps[a.mapId]){this.dataState.player.mapId=a.mapId;this.dataState.player.x=a.x??this.config.maps[a.mapId].spawn.x;this.dataState.player.y=a.y??this.config.maps[a.mapId].spawn.y;}});}
  private spawnEnemy(zone:GameProtocol['maps'][string]['spawns'][number]):void {const def=this.config.monsters[zone.monsterId],enemy=this.enemies.create(Phaser.Math.Between(zone.x,zone.x+zone.width),Phaser.Math.Between(zone.y,zone.y+zone.height),def.texture) as Phaser.Physics.Arcade.Sprite;enemy.setData({monsterId:zone.monsterId,zone:zone.id,hp:def.stats.maxHp});}
  private attack(time:number):void {if(time-this.lastAttack<this.config.combat.attackCooldownMs)return;this.lastAttack=time;const slash=this.add.circle(this.player.x,this.player.y,this.config.combat.attackRange*.6,0xffefb0,.38).setDepth(3);this.tweens.add({targets:slash,scale:1.55,alpha:0,duration:180,onComplete:()=>slash.destroy()});const stats=playerStats(this.config,this.dataState.player.level);this.enemies.getChildren().forEach(c=>{const e=c as Phaser.Physics.Arcade.Sprite;if(!e.active||Phaser.Math.Distance.BetweenPoints(this.player,e)>=this.config.combat.attackRange)return;const def=this.config.monsters[String(e.getData('monsterId'))],damage=Math.max(1,stats.attack-def.stats.defense),hp=Number(e.getData('hp'))-damage;e.setData('hp',hp).setTintFill(0xffffff);this.time.delayedCall(90,()=>e.active&&e.clearTint());if(hp<=0)this.defeatEnemy(e);});}
  private defeatEnemy(enemy:Phaser.Physics.Arcade.Sprite):void {const id=String(enemy.getData('monsterId')),def=this.config.monsters[id];enemy.destroy();this.dataState.world.defeated[id]=(this.dataState.world.defeated[id]??0)+1;this.progressByEvent('kill',id);this.addXp(def.xp);def.drops.forEach(drop=>{if(Math.random()<=drop.chance)this.addItem(drop.itemId,Phaser.Math.Between(drop.min,drop.max));});this.toast(`${def.name} 처치 · 경험치 +${def.xp}`);this.persist();}
  private updateEnemies(time:number):void {if(this.frozen)return;this.enemies.getChildren().forEach(c=>{const e=c as Phaser.Physics.Arcade.Sprite;if(!e.active)return;const def=this.config.monsters[String(e.getData('monsterId'))],distance=Phaser.Math.Distance.BetweenPoints(this.player,e),body=e.body as Phaser.Physics.Arcade.Body;if(distance<def.aggroRange)this.physics.moveToObject(e,this.player,def.speed);else body.setVelocity(0);if(distance<32&&time-this.lastHurt>this.config.combat.invulnerabilityMs){this.lastHurt=time;const stats=playerStats(this.config,this.dataState.player.level),damage=Math.max(1,def.stats.attack-stats.defense);this.dataState.player.hp=Math.max(0,this.dataState.player.hp-damage);this.cameras.main.shake(90,.007);if(this.dataState.player.hp<=0)this.respawn();this.emitState();}});}
  private respawn():void {const map=this.config.maps[this.dataState.player.mapId];this.dataState.player.hp=playerStats(this.config,this.dataState.player.level).maxHp;this.player.setPosition(map.spawn.x,map.spawn.y);this.toast('쓰러졌습니다. 지역 입구에서 다시 시작합니다.');this.persist();}
  private checkExits():void {if(this.transitioning)return;const map=this.config.maps[this.dataState.player.mapId],exit=map.exits.find(e=>Phaser.Geom.Rectangle.Contains(new Phaser.Geom.Rectangle(e.x-e.width/2,e.y-e.height/2,e.width,e.height),this.player.x,this.player.y));if(!exit)return;this.transitioning=true;this.dataState.player.mapId=exit.to;this.dataState.player.x=exit.spawnX;this.dataState.player.y=exit.spawnY;this.progressByEvent('visit',exit.to);this.persist();this.cameras.main.fadeOut(220,10,18,20);this.time.delayedCall(240,()=>this.scene.restart());}
  private progressByEvent(type:'kill'|'talk'|'visit'|'collect',targetId:string,amount=1):void {Object.entries(this.config.quests).forEach(([id,q])=>{const progress=this.dataState.world.quests[id];if(progress?.status!=='active')return;q.objectives.filter(o=>o.type===type&&o.targetId===targetId).forEach(o=>this.progressObjective(id,o.id,amount));});}
  private progressObjective(questId:string,objectiveId:string,amount:number):void {const progress=this.dataState.world.quests[questId],def=this.config.quests[questId];if(!progress||progress.status!=='active')return;const objective=def.objectives.find(o=>o.id===objectiveId);if(!objective)return;progress.objectives[objectiveId]=Math.min(objective.target,(progress.objectives[objectiveId]??0)+amount);if(def.objectives.every(o=>(progress.objectives[o.id]??0)>=o.target))progress.status='ready';}
  private completeQuest(id:string):void {const q=this.dataState.world.quests[id],def=this.config.quests[id];if(!q||q.status==='completed')return;q.status='completed';if(!q.rewarded){this.addXp(def.rewards.xp??0);Object.entries(def.rewards.items??{}).forEach(([item,n])=>this.addItem(item,n));q.rewarded=true;this.toast(`퀘스트 완료 · ${def.title}`);}}
  private addItem(id:string,amount:number):void {const def=this.config.items[id];if(!def)return;const before=this.dataState.player.inventory[id]??0;this.dataState.player.inventory[id]=Phaser.Math.Clamp(before+amount,0,def.maxStack);if(amount>0){this.progressByEvent('collect',id,amount);this.toast(`${def.name} +${amount}`);}}
  private addXp(amount:number):void {this.dataState.player.xp+=amount;const curve=this.config.player.xpCurve;while(this.dataState.player.level<curve.length&&this.dataState.player.xp>=curve[this.dataState.player.level]){this.dataState.player.level++;const stats=playerStats(this.config,this.dataState.player.level);this.dataState.player.hp=stats.maxHp;this.toast(`레벨 ${this.dataState.player.level} 달성!`);}}
  private persist():void {this.dataState.playTime+=Math.floor((Date.now()-this.startedAt)/1000);this.startedAt=Date.now();this.onChange(this.snapshot());}
  private emitState():void {if(!this.player)return;const active=Object.entries(this.dataState.world.quests).find(([,q])=>q.status==='active'||q.status==='ready');let objective='새로운 의뢰를 찾아보세요';if(active){const def=this.config.quests[active[0]],q=active[1],next=def.objectives.find(o=>(q.objectives[o.id]??0)<o.target);objective=q.status==='ready'?`${def.giver}에게 보고하세요`:next?`${next.label} ${q.objectives[next.id]??0}/${next.target}`:def.title;}const stats=playerStats(this.config,this.dataState.player.level),map=this.config.maps[this.dataState.player.mapId],minimap:MinimapState={player:{x:this.player.x,y:this.player.y},npcs:map.npcs.map(n=>({x:n.x,y:n.y})),enemies:this.enemies?.getChildren().filter(e=>(e as Phaser.Physics.Arcade.Sprite).active).map(e=>({x:(e as Phaser.Physics.Arcade.Sprite).x,y:(e as Phaser.Physics.Arcade.Sprite).y}))??[],exits:map.exits.map(e=>({x:e.x,y:e.y}))};this.events.emit('state',{hp:this.dataState.player.hp,maxHp:stats.maxHp,level:this.dataState.player.level,xp:this.dataState.player.xp,nextXp:this.config.player.xpCurve[this.dataState.player.level]??this.dataState.player.xp,attack:stats.attack,defense:stats.defense,objective,mapName:map.name,quests:structuredClone(this.dataState.world.quests),inventory:{...this.dataState.player.inventory},minimap} satisfies GameViewState);}
  private toast(message:string):void {this.events.emit('toast',message);}
}
